name:                adventofcode2019
version:             0.1.0.0
github:              "culturedsys/adventofcode2019"
license:             GPL-3
author:              "Tim Fisken"
maintainer:          "contact@timfisken.org"
copyright:           "2019 Tim Fisken"

extra-source-files:
- README.md
- LICENSE

dependencies:
- base >= 4.7 && < 5
- hspec
- filepath
- containers
- mtl
- sort
- monad-loops
- split
- QuickCheck

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  day1:
    main: Day1Main.hs
    source-dirs: app
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day1Main

  day2:
    main: Day2Main.hs
    source-dirs: app
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day2Main
  
  day3:
    main: Day3Main.hs
    source-dirs: app
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day3Main

  day4:
    main: Day4Main.hs
    source-dirs: app
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day4Main


tests:
  intcode-test:
    main: IntCodeSpec.hs
    source-dirs: test
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is IntCodeSpec

  day1-test:
    main: Day1Spec.hs
    source-dirs: test
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day1Spec
    
  day2-test:
    main: Day2Spec.hs
    source-dirs: test
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day2Spec

  day3-test:
    main: Day3Spec.hs
    source-dirs: test
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day3Spec

  day4-test:
    main: Day4Spec.hs
    source-dirs: test
    dependencies: 
    - adventofcode2019
    ghc-options:
    - -main-is Day4Spec
